cites = ['kathmandu', 'hetauda', 'chitwan', 'biratnagar', 'ithari']
print("Here is the original list:")
print(cites)
print()
print("Here is the sorted list:")
print(sorted(cites))
print()
print("Again the Original list:")
print(cites)
print()
print("Here is the reversed list:")
print(sorted(cites))
print()
print("Here is the list with the reverse method:")
cites.reverse()
print(cites)
print()
print("Here is the list with the reverse method for the original outcome:")
cites.reverse()
print(cites)
print()
print("Here is the length of the list:")
print(len(cites))
print()
print("Poping an Element in the list:")
print(cites.pop())
print()
print("Poping an Element in the list with the define index:")
print(cites.pop(1))
print()
print("Inserting an element in the list:")
cites.insert(1,'taudaha')
print(cites)
print()
print("Appending an Element in the list:")
cites.append('kirtipur')
print(cites)
print()
print("Using the string methods in the list:")
print(cites[0].title())
print()